all: hw5_binomial hw5_monte hw5_bn1
	g++ hw5_binomial.cpp -o hw5_binomial -std=c++11 -O2
	g++ hw5_monte.cpp -o hw5_monte -std=c++11 -O2
	g++ hw5_bn1.cpp -o hw5_bn1 -std=c++11 -O1

clean:
	rm hw5_binomial hw5_monte hw5_bn1
